from mathix.arithmetic import *
from mathix.algebra import *
from mathix.statistics import *
from mathix.discrete_probability import *
from mathix.geometry_2d import *
from mathix.trigonometry import *
from mathix.calculus import *
from mathix.matrix import *
from mathix.random import random
from mathix.noise2 import noise2
from mathix.ai_logic import *
from mathix.interpolation import *
from mathix.physics_2d import *