from mathix.m_arithmetic import *
from mathix.m_algebra import *
from mathix.m_statistics import *
from mathix.m_discrete_probability import *
from mathix.m_geometry2 import *
from mathix.m_trigonometry import *
from mathix.m_calculus import *
from mathix.m_matrix import *
from mathix.m_random import m_random
from mathix.m_noise2 import m_noise2
from mathix.m_ai_logic import *
from mathix.m_interpolation import *
from mathix.m_physics2 import *
from mathix.m_voronoi2 import *