from arithmetic import *
from algebra import *
from mathix.statistics import *
from discrete_probability import *
from geometry_2d import *
from trigonometry import *
from calculus import *
from matrix import *
from mathix.random import random
from noise2 import noise2
from ai_logic import *
from interpolation import *
from physics_2d import *